# Site settings
title: IBW High School Printmaking
description: Exploring creativity through printmaking at Ida B. Wells High School
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aramansell.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

include: ['_pages', '_data']
# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Other settings can be added here...